// Portfolio data — Raz Silberman

const COMPANIES = [
  {
    id: 'quill',
    name: 'Quill',
    tagline: 'Knowledge management for support teams',
    description: 'B2B SaaS · Tel Aviv. The KMS lighthouse for support orgs — writers, agents, admins, and end-users sharing one knowledge graph.',
    role: 'Senior → Lead Product Designer',
    when: '2023 — Present',
    accent: 'sage',
    swatch: { from: '#1A1F1B', to: '#0C100D', mark: '#3E5142' },
    projectIds: ['help-center', 'design-system', 'product-redesign'],
  },
  {
    id: 'northbeam',
    name: 'Northbeam',
    tagline: 'B2B2C platform — admins set up, employees live in it',
    description: 'Two-audience SaaS, sold to companies and used daily by their employees. Owned the analytics squad and rebuilt first-run.',
    role: 'Product Designer',
    when: '2021 — 2023',
    accent: 'blue',
    swatch: { from: '#181B1D', to: '#0B0D0E', mark: '#3E4448' },
    projectIds: ['platform-redesign'],
  },
];

const PROJECTS = [
  {
    id: 'help-center',
    n: '01',
    title: 'Help Center',
    subtitle: 'A customizable B2B2C Help Center',
    role: 'Lead Designer (solo)',
    year: '2024 — ongoing',
    timeline: 'Ongoing, multi-phase',
    platform: 'Web — admin + end-user, responsive',
    team: 'Solo designer · PMs · engineers',
    sector: 'B2B SaaS · Enterprise knowledge',
    kind: 'B2B SaaS',
    company: 'KMS Lighthouse',
    tile: 'wide',
    summary: 'A customizable Help Center that gave business admins full control over their self-service site — no developers required. Replaced a legacy product that wasn\'t winning customers.',
    heroImage: 'help center/36.png',
    swatch: { from: '#1A1F1B', to: '#0C100D', mark: '#3E5142' },
    sections: [
      { id: 'context', title: 'Context', body: [
        'KMS Lighthouse is an enterprise knowledge management platform used by companies like DHL, GE Healthcare, AIG, and Allianz to power their call centers, self-service portals, and internal knowledge bases.',
        'The Help Center is one of Lighthouse\'s external products. It lets businesses spin up a fully branded self-service site for their end users — pulling content directly from the Lighthouse platform their teams already use, so no separate site, no data migration, no parallel content workflow.',
        'It\'s sold separately from the core platform, but built to extend it. For existing customers it\'s an upsell; for new ones it\'s a differentiator against competitors who can\'t offer the same end-to-end loop.',
      ]},
      { id: 'role', title: 'Role & Approach', body: [
        'I was the sole designer on this project, working alongside product managers and engineers across multiple delivery phases.',
        'That meant owning every part of the design — research, IA, flows, wireframes, UI, design system contributions, and handoff. It also meant balancing two very different audiences inside one product: the business admin configuring the Help Center, and the end user trying to find an answer fast.',
      ]},
      { id: 'problem', title: 'The Problem',
        body: ['Lighthouse had an existing Help Center product, but it wasn\'t selling. The reasons were structural, not cosmetic:'],
        list: [
          { label: 'Complex setup.', text: 'Every change — from copy to layout to branding — had to be made in the backend by a specialized dev team. Admins couldn\'t touch their own site.' },
          { label: 'Usability issues.', text: 'Most end users accessed help on mobile, but the existing design wasn\'t responsive. Articles were hard to find, support tickets went up instead of down, and the whole experience felt dated.' },
          { label: 'Limited customization.', text: 'The product offered almost no flexibility. Businesses couldn\'t make the Help Center feel like their own brand, which made it a hard sell to enterprise clients who care about brand consistency.' },
        ],
        outro: ['The result: a product positioned as a competitive differentiator that wasn\'t actually differentiating anything. Existing clients passed on the upsell. New prospects went elsewhere.'],
        media: [
          { src: 'help center/3.png', caption: 'The legacy Help Center', kind: 'wide' },
        ],
      },
      { id: 'goals', title: 'Goals',
        body: ['Three goals shaped the redesign, each tied directly to one of the problems above:'],
        list: [
          { label: 'Put admins in control.', text: 'Give business admins full ownership of their Help Center — setup, content, and maintenance — without needing dev or support involvement.' },
          { label: 'Design mobile-first.', text: 'Rebuild the end-user experience around how people actually use it: on their phone, looking for one answer, fast.' },
          { label: 'Make it brandable.', text: 'Give admins meaningful control over branding and layout so the Help Center could feel like a natural extension of their own site, not a third-party tool bolted on.' },
        ],
      },
      { id: 'research', title: 'Research',
        body: ['To ground the redesign in real needs rather than assumptions, I ran four research tracks in parallel:'],
        list: [
          { label: 'Stakeholder interviews', text: 'with business customers, focused on setup pain points, customization needs, and desired features.' },
          { label: 'User interviews', text: 'with both admins and end users, surfacing where the existing Help Center broke down on each side.' },
          { label: 'Competitive analysis', text: 'of other self-service help platforms, identifying both table-stakes patterns and opportunities to differentiate.' },
          { label: 'Surveys', text: 'with both audiences to validate qualitative findings at scale.' },
        ],
      },
      { id: 'insights', title: 'Key Insights',
        body: ['Three insights drove every design decision that followed:'],
        list: [
          { label: 'Brand customization isn\'t a nice-to-have.', text: 'Enterprise clients won\'t ship a Help Center that doesn\'t feel like theirs. Layout, color, typography, content presentation — admins need real control, and they need it without writing code.' },
          { label: 'Navigation is the product.', text: 'For end users, the Help Center is its search and category structure. Everything else is decoration. Getting findability right was the single biggest unlock.' },
          { label: 'The UI needed to earn its place.', text: 'The old product looked like an admin tool. The new one needed to look like something a brand would proudly link from their main site.' },
        ],
      },
      { id: 'flows', title: 'User Flows',
        body: [
          'I mapped flows for both audiences in parallel — admins configuring the site, end users navigating it — to make sure neither experience was an afterthought of the other.',
          'The exercise surfaced where the two audiences\' needs intersected (and where they didn\'t), which shaped how I structured the admin panel later: a customization model that gives admins real power without exposing end users to its complexity.',
        ],
        media: [
          { src: 'help center/8.png', caption: 'User flow — admin + end-user paths', kind: 'wide' },
        ],
      },
      { id: 'wireframing', title: 'Wireframing',
        body: [
          'Wireframes covered both sides of the product: the admin\'s setup and customization screens, and the end user\'s homepage, category, article, and search experiences.',
          'The goal at this stage was structural — making sure information density, navigation, and content hierarchy worked before any visual design entered the picture.',
        ],
        media: [
          { src: 'help center/9.png', caption: 'Wireframe grid', kind: 'wide' },
        ],
      },
      { id: 'admin', title: 'The Admin Experience',
        body: [
          'The admin side is where this product had to earn its keep. If admins couldn\'t set up and customize the Help Center themselves, nothing else mattered.',
          'I designed the admin panel as a series of focused settings: site configuration, localization, content management, and a dedicated customization panel for branding.',
        ],
        subsections: [
          {
            id: 'admin-settings',
            title: 'Settings',
            body: ['A dedicated section for managing the Help Center\'s website settings, language support, and integration with the Lighthouse platform — including real-time content sync.'],
            media: [
              { src: 'help center/11.png', kind: 'sq' },
              { src: 'help center/12.png', kind: 'sq' },
              { src: 'help center/13.png', kind: 'sq' },
              { src: 'help center/14.png', kind: 'sq' },
              { src: 'help center/15.png', kind: 'sq' },
            ],
          },
          {
            id: 'admin-custom',
            title: 'Customization panel',
            body: ['The customization panel gives admins direct control over their site\'s brand and structure: logo, favicon, header, footer, color system, card styles, and content layout. Non-technical users can change how the Help Center looks and behaves without touching a line of code.'],
            media: [
              { src: 'help center/26.png', caption: 'Customization panel breakdown', kind: 'wide' },
            ],
          },
          {
            id: 'admin-onboarding',
            title: 'Homepage setup with guided onboarding',
            body: ['First-time admins are walked through localization, language management, and translation workflows via inline guides — turning what was previously a developer task into a self-serve flow.'],
            media: [
              { src: 'help center/17.png', kind: 'sq' },
              { src: 'help center/18.png', kind: 'sq' },
              { src: 'help center/19.png', kind: 'sq' },
              { src: 'help center/20.png', kind: 'sq' },
              { src: 'help center/21.png', kind: 'sq' },
              { src: 'help center/22.png', kind: 'sq' },
            ],
          },
        ],
      },
      { id: 'enduser', title: 'The End-User Experience',
        body: [
          'For end users, success is one thing: finding the right answer fast.',
          'The redesigned homepage leads with a hero search anchored in the brand\'s own visual identity, followed by category cards that map to the most common end-user tasks. Articles live in a clean reading layout with related links, helpful/not-helpful feedback, and step-by-step content where it applies.',
        ],
        media: [
          { src: 'help center/36.png', caption: 'Final homepage', kind: 'wide' },
          { src: 'help center/40.png', caption: 'Article view', kind: 'wide' },
        ],
        outro: ['The shift from the previous product is dramatic: the old Help Center looked like a templated FAQ widget. The new one feels like part of the brand\'s own site.'],
        beforeAfter: {
          before: { src: 'help center/3.png',  label: 'Before — legacy product' },
          after:  { src: 'help center/36.png', label: 'After — new Help Center' },
        },
      },
      { id: 'responsive', title: 'Responsive',
        body: ['Mobile-first wasn\'t a slogan — it was a constraint that shaped every layout decision. The end-user experience scales cleanly across desktop, tablet, and mobile, with the same search-first hierarchy at every breakpoint.'],
        media: [
          { src: 'help center/33.png', caption: 'Desktop · tablet · mobile', kind: 'wide' },
        ],
      },
      { id: 'outcome', title: 'Outcome', placeholder: true,
        body: ['Outcome content to fill in together — likely a combination of: first fully customizable Help Center in the Lighthouse product line; existing clients now actively requesting the new version after passing on the old one; new clients signing on partially because of the Help Center; admins able to self-serve setup without dev or support involvement; positive feedback from sales and CS teams.'],
      },
      { id: 'reflection', title: 'Reflection', placeholder: true,
        body: ['One honest sentence on what I learned or would do differently — to fill in.'],
      },
    ],
    gallery: [
      { src: 'help center/36.png', label: 'Final homepage',       kind: 'wide' },
      { src: 'help center/26.png', label: 'Customization panel',  kind: 'sq'   },
      { src: 'help center/40.png', label: 'Article view',         kind: 'sq'   },
      { src: 'help center/33.png', label: 'Responsive',           kind: 'tall' },
      { src: 'help center/8.png',  label: 'User flows',           kind: 'tall' },
    ],
  },
  {
    id: 'design-system',
    n: '02',
    title: 'Telos Design System',
    subtitle: 'A shared language across six product surfaces',
    role: 'Design Systems Lead',
    year: '2023 — 2024',
    timeline: 'Apr 2023 — Feb 2024',
    platform: 'Web · iOS · Android',
    team: '2 designers, 3 engineers',
    sector: 'Internal platform',
    kind: 'Design system',
    tile: 'tall',
    summary: 'Built the company\'s first proper design system from the inside out — tokens, primitives, patterns, governance — and migrated four shipped products onto it without freezing a single feature team.',
    swatch: { from: '#1F1A14', to: '#13100C', mark: '#5A4A33' },
    sections: [
      { id: 'context', title: 'Context', body: [
        'Six product teams, three platforms, and exactly one shared component: the company logo. Buttons came in 14 visually distinct flavors. Spacing followed nobody\'s scale.',
        'Leadership wanted "a design system." What that meant in practice was the much harder thing: a way for six teams to agree without anyone losing autonomy.',
      ]},
      { id: 'tokens', title: 'Tokens first', body: [
        'I started at the bottom — a single source of truth for color, spacing, type, and motion, exported to CSS variables, Swift, and Compose from one JSON spec.',
        'Tokens shipped before any components did. That decision made the rest of the project possible: teams could adopt the new visual language gradually, one variable at a time, without waiting for a button.',
      ]},
      { id: 'primitives', title: 'Primitives, not pages', body: [
        'Resisted the temptation to ship a "card component" or a "form component." Instead: layout primitives (Stack, Cluster, Grid), surface primitives (Box, Sheet, Divider), and a small set of true components (Button, Field, Menu, Toast).',
        'Pages and patterns live in product repos — not in the system. The system is the floor; product teams build the building.',
      ]},
      { id: 'governance', title: 'Governance', body: [
        'Weekly office hours, a public Linear board for requests, and a clear rule: anything used in 3+ products gets promoted to the system; anything in 1 stays local.',
        'The hardest part wasn\'t the components — it was teaching everyone that "this should be in the system" is a question, not a demand.',
      ]},
      { id: 'outcomes', title: 'What changed', kind: 'outcomes', items: [
        { num: '4 → 1', label: 'Button implementations' },
        { num: '−68%', label: 'Time to ship new screens' },
        { num: '0', label: 'Frozen feature teams during migration' },
      ]},
    ],
    gallery: [
      { kind: 'wide', label: 'Token spec', tone: '#15110C' },
      { kind: 'sq', label: 'Primitives', tone: '#13100B' },
      { kind: 'sq', label: 'Components', tone: '#16120D' },
    ],
  },
  {
    id: 'product-redesign',
    n: '03',
    title: 'Product Redesign',
    subtitle: 'A full redesign that pivoted mid-project',
    role: 'Senior Designer',
    year: '2024 — ongoing',
    timeline: '2024 — ongoing',
    platform: 'Web — admin + end-user, responsive',
    team: 'In-house design team · PMs · engineers',
    sector: 'B2B SaaS · Enterprise knowledge',
    kind: 'B2B SaaS',
    company: 'KMS Lighthouse',
    tile: 'sq',
    summary: 'A full redesign of the KMS Lighthouse platform that pivoted mid-project — and got better because of it.',
    heroImage: 'redesign/35.png',
    swatch: { from: '#1B1820', to: '#0E0C13', mark: '#4A4458' },
    sections: [
      { id: 'context', title: 'Context', body: [
        'KMS Lighthouse is an enterprise knowledge management platform used by companies like DHL, GE Healthcare, AIG, and Allianz to power their call centers, self-service portals, and internal knowledge bases. It\'s the core product the company is built on.',
        'But by 2024, the platform was showing its age. Years of feature additions, multiple outsourced design teams, and no unified design system had produced an interface that was cluttered, inconsistent, and increasingly hard for users — and the company — to maintain.',
        'We set out to redesign it. What we delivered wasn\'t what we started with.',
      ]},
      { id: 'role', title: 'Role & Approach', body: [
        'I worked on this as a Senior Designer alongside a small in-house design team, partnering closely with product and engineering across multiple phases.',
        'It was a team effort with no single lead, but each designer owned distinct surfaces end to end. My focus was on the content management experience — the part of the product where business users spend most of their day — and I designed the field component system (input fields and view-only fields) that became the foundation for consolidating the platform\'s separate editing and end-user views. I also co-designed the responsive grid that underpins the whole redesign.',
        'The work below reflects what I designed and led on.',
      ]},
      { id: 'problem', title: 'The Problem',
        body: ['The platform had three structural issues that compounded each other:'],
        list: [
          { label: 'Cluttered interface.', text: 'The UI was overloaded with information and lacked a clear grid system, making it difficult for users to focus on critical tasks.' },
          { label: 'Inconsistency.', text: 'Built over several years without a unified design system — and through various outsourced designers — the platform had drifted into a confusing, inconsistent experience. The same pattern appeared in three different forms across the product.' },
          { label: 'Performance issues.', text: 'Years of layered feature additions had created redundancy, with multiple features serving the same purpose. The system had slowed down, both technically and cognitively.' },
        ],
        problemRows: [
          { label: 'No grid',       images: ['redesign/no-grid-1.png', 'redesign/no-grid-2.png'] },
          { label: 'Inconsistent',  images: ['redesign/inconsistent-1.png', 'redesign/inconsistent-2.png'] },
          { label: 'Overwhelming',  images: ['redesign/overwhelming-1.png'] },
        ],
      },
      { id: 'goals', title: 'Initial Goals',
        body: ['The original ambition was big. Five goals to fundamentally reshape the product:'],
        list: [
          { label: 'Simplify the interface.', text: 'Reduce cognitive load and improve task completion.' },
          { label: 'Build for consistency and scale.', text: 'Establish a unified design system the company could grow with.' },
          { label: 'Optimize for mobile.', text: 'Make the platform genuinely responsive, not just adapted.' },
          { label: 'Consolidate features.', text: 'Merge redundant features that had drifted apart over years of patches.' },
          { label: 'Enhance collaboration.', text: 'Add comments, tagging, and simultaneous editing — features long requested by users.' },
        ],
        outro: ['These goals were the right destination. They turned out not to be the right route.'],
      },
      { id: 'research', title: 'Research',
        body: ['To make sure the redesign was grounded in real needs, we ran four research tracks:'],
        list: [
          { label: 'Stakeholder interviews', text: 'to understand business priorities and the constraints the redesign had to respect.' },
          { label: 'User interviews', text: 'with existing users to surface specific usability pain points.' },
          { label: 'Competitive analysis', text: 'of other leading knowledge management platforms to identify table-stakes patterns and gaps we could differentiate on.' },
          { label: 'Usability evaluations', text: 'of the current system to pinpoint the highest-friction moments.' },
        ],
      },
      { id: 'insights', title: 'Key Insights',
        body: ['Four insights emerged from the research, and each one shaped a decision later in the project:'],
        list: [
          { label: 'Editing felt disconnected from reading.', text: 'Lighthouse has three distinct user types — admins, content managers, and end users (typically call center reps) — and each one was looking at a completely different interface. The content managers had it worst: every time they updated a piece of content, they had to jump to a separate tab or window to see what the end user would actually see. That gap created constant low-grade anxiety — did I just break something? — and slowed work down because every edit required a context switch to verify it. Notion became our reference point here: editing and reading should feel nearly identical, so you trust what you\'re writing.' },
          { label: 'Navigation was disorienting.', text: 'Users frequently lost track of where they were in the product. The information architecture had grown organically, not deliberately.' },
          { label: 'Collaboration was a real gap.', text: 'There was strong demand for the ability to share notes, comment on documents, and work alongside teammates — features competitors offered and Lighthouse didn\'t.' },
          { label: 'Mobile didn\'t really work.', text: 'The platform wasn\'t optimized for smaller screens, which had become a daily friction for users in the field.' },
        ],
      },
      { id: 'flows', title: 'User Flows',
        body: [
          'Working closely with product, I mapped key task flows to make sure the new product simplified the most common journeys rather than just visually polishing them.',
          'A particular focus: the article versioning model (Draft → Active → Past versions), which was central to how content managers worked but had no clear conceptual model in the old product.',
        ],
        media: [
          { diagram: 'user-flow', caption: 'Article versioning flow — Draft → Active → Past', kind: 'wide' },
        ],
      },
      { id: 'wireframing', title: 'Wireframing',
        body: [
          'Wireframes explored layout structures, content hierarchy, and how responsiveness would work across devices — particularly for the densest screens like the article editor.',
        ],
        sideMedia: { src: 'redesign/wireframing.png', caption: 'Wireframes' },
      },
      { id: 'prototyping', title: 'Prototyping',
        body: [
          'I built interactive prototypes to validate flows, test interactions, and gather early feedback from product and engineering before committing to high-fidelity design.',
        ],
        sideMedia: { src: 'redesign/scrapped_design_prototype.mov', caption: 'Prototype — early interactions' },
      },
      { id: 'testing', title: 'Usability Testing',
        body: [
          'We tested the prototypes with existing users to validate design decisions before going further.',
          'The testing surfaced something we hadn\'t expected — and that became the inflection point of the entire project.',
        ],
      },
      { id: 'setbacks', title: 'Setbacks',
        body: [
          'The redesign was working, on paper. The flows were cleaner. The interface was simpler. The new patterns were more consistent.',
          'But four problems showed up at the same time, and together they killed the original plan:',
        ],
        list: [
          { label: 'Dev estimates came in too high.', text: 'Implementation projected three full-time engineering teams working for nine months. That timeline didn\'t fit any reasonable product roadmap.' },
          { label: 'Usability testing flagged adoption risk.', text: 'Every individual change in the redesign came from requests users had made over the years — but the cumulative effect of shipping them all together was too far from what those same users could accept. They\'d built workflows around the old patterns, and the data suggested low adoption if we shipped it as one release.' },
          { label: 'Users needed features now.', text: 'The roadmap had specific features users were urgently waiting on. A nine-month redesign cycle meant putting those on hold.' },
          { label: 'Two products in parallel was untenable.', text: 'Not all users wanted to upgrade. Supporting both interfaces during a long migration would have meant effectively maintaining two different products.' },
          { label: 'Data migration was a non-starter.', text: 'Consolidating certain features would have created significant downstream problems migrating existing client data — a cost we couldn\'t justify imposing on customers who had years of content invested in the old structure.' },
        ],
        outro: ['We had a choice: push through and hope, or pivot.'],
      },
      { id: 'pivot', title: 'The Pivot',
        body: ['We pivoted. The full redesign was scaled back. Three goals stayed:'],
        list: [
          { label: 'Simplify the interface.', text: '' },
          { label: 'Build for consistency and scale.', text: '' },
          { label: 'Optimize for mobile.', text: '' },
        ],
        outro: [
          'The other two — consolidating redundant features and adding collaboration tools — were paused, not killed. They\'d return in later phases, sequenced around what users actually needed first.',
          'The new approach: a focused facelift that improved the parts of the product users touched most, on the foundation of a real design system and grid, without breaking the workflows people relied on.',
        ],
      },
      { id: 'facelift-enduser', title: 'End-User Experience',
        group: 'facelift', groupLabel: 'The Facelift',
        body: [
          'The facelift focused on the moments users hit most — homepage, search, article view, content editing — and brought them onto a shared visual and structural foundation.',
          'The homepage kept what worked (search-first, customer\'s branded content, news, employee spotlight) but cleaned up the chrome around it. The article view got a clearer hierarchy, persistent navigation, and a right-side rail that surfaces related content and AI assistance.',
        ],
        media: [
          { src: 'redesign/23.png', caption: 'Redesigned homepage', kind: 'wide' },
          { src: 'redesign/35.png', caption: 'Article view', kind: 'wide' },
        ],
      },
      { id: 'facelift-grid', title: 'Responsive Grid System',
        group: 'facelift', groupLabel: 'The Facelift',
        body: [
          'I co-designed the responsive grid system that became the foundation for the redesign — and the basis for the design system going forward.',
          'The grid handles the full range of platform states: no side panels, left side panel, right side panel, both side panels — each across five breakpoints. It\'s the first time the product has had a unified spatial system that designers and engineers can both work from.',
        ],
        sideMedia: { src: 'redesign/responsive-grid.png' },
        inlineDemo: 'grid',
        inlineDemoCaption: 'Responsive grid — panel states × breakpoints (interactive)',
      },
      { id: 'facelift-consolidation', title: 'Consolidating the Editing Experience',
        group: 'facelift', groupLabel: 'The Facelift',
        body: [
          'The biggest shift in the facelift — and the one I\'m proudest of — was closing the gap between editing and reading.',
          'Lighthouse has three user types looking at different interfaces: admins, content managers, and end users. Of those, the content manager has the highest cognitive load — they\'re writing the content that powers everyone else\'s work — and the old product made their job harder by showing them an editor that looked nothing like what their readers would see. Every save was followed by a tab switch to verify nothing had broken.',
          'In the facelift, the content manager\'s view and the end user\'s view sit on the same structural foundation. Same field types, same layout, same content blocks. The editor sees what the reader will see — minus the editing affordances — so they can write with confidence instead of constantly verifying.',
          'We can\'t fully replicate the Notion model (Lighthouse is a much more complex system with more field types, more permission states, and more content structures), but we could borrow the principle: minimize the deviation between writing and reading.',
        ],
        outro: [
          'My specific contribution: I designed the field components that made this consolidation possible — the input fields and the view-only fields — and the interaction model that governs how a single field behaves across edit and view-only states. The system-level decision to consolidate views could only ship if the components underneath it were designed to behave coherently across both modes. That\'s the piece I owned.',
        ],
        media: [
          { src: 'redesign/58.png', caption: 'Content manager view vs. end-user view — same structural foundation', kind: 'wide' },
          { src: 'redesign/32.png', caption: 'Field components — table view', kind: 'sq' },
          { src: 'redesign/50.png', caption: 'Editor with field-level controls', kind: 'sq' },
        ],
      },
      { id: 'facelift-sidebar', title: 'Right Sidebar & AI Assistant',
        group: 'facelift', groupLabel: 'The Facelift',
        body: [
          'A new right sidebar was added in editing mode, designed to surface contextual tools without cluttering the main workspace — history, analytics, permissions, and properties, each opening as a focused panel.',
          'This also set the stage for the AI Assistant, which sits in the same sidebar real estate and lets users ask questions of the content directly inside the article they\'re working on.',
        ],
        parallax: true,
        sideMedia: { placeholder: true, caption: 'Right sidebar — contextual panels' },
        media: [
          { placeholder: true, caption: 'AI Assistant — in-article Q&A' },
          { src: 'redesign/new-design-sidebar.mov', caption: 'Sidebar prototype' },
        ],
      },
      { id: 'scrapped', title: 'The Scrapped Design',
        body: [
          'The original ambitious redesign isn\'t lost — it\'s documented and preserved as future direction for the platform. Not shipped, but informing future work.',
        ],
        sideGallery: [
          { src: 'redesign/scrapped-1-collapsed.png',  caption: 'Sidebar collapsed' },
          { src: 'redesign/scrapped-2-sidebar.png',    caption: 'Field details sidebar' },
          { src: 'redesign/scrapped-3-history.png',    caption: 'History panel' },
          { src: 'redesign/scrapped-4-analytics.png',  caption: 'Analytics panel' },
          { src: 'redesign/scrapped-5-properties.png', caption: 'Properties panel' },
          { src: 'redesign/scrapped-6-hidden.png',     caption: 'End user view' },
        ],
      },
      { id: 'outcome', title: 'Outcome & Key Takeaways',
        body: [
          'Although the full redesign was ultimately scrapped, the process gave us a much clearer understanding of the platform\'s real constraints, user needs, and technical realities. The pivot — from a complete overhaul to a focused facelift — produced something that better aligned with what users and the business could actually absorb.',
          'The shipped facelift improves the highest-traffic moments of the product, runs on a unified responsive grid system, and meaningfully closes the gap between content managers and the end users they\'re writing for. The structural groundwork is now in place for future phases — including the feature consolidation and collaboration work that got paused.',
        ],
        list: [
          { label: 'Prioritize user needs through consistent research and testing.', text: 'The feedback gathered throughout the project was what made the pivot possible — and the right call. Without it, we\'d have shipped a redesign users wouldn\'t have adopted.' },
          { label: 'A simple, intuitive interface is what reduces frustration — not novelty.', text: 'Small, targeted changes to existing user flows significantly improved usability in testing.' },
          { label: 'Components are where systems live or die.', text: 'Decisions like "consolidate the editing and reading views" sound like UX architecture, but they only work if the underlying components are designed to behave coherently across every context they appear in. The system-level call and the component-level work are inseparable.' },
          { label: 'Collaboration tools should be integrated seamlessly, not bolted on.', text: 'Pausing the collaboration work was the right call, because doing it well requires more design space than a facelift allows. It\'s worth shipping later, properly, rather than now, poorly.' },
        ],
      },
    ],
    gallery: [
      { src: 'redesign/23.png', label: 'Redesigned homepage',        kind: 'wide' },
      { src: 'redesign/35.png', label: 'Article view',               kind: 'sq'   },
      { src: 'redesign/58.png', label: 'CM view vs. end-user view',  kind: 'sq'   },
      { src: 'redesign/30.png', label: 'Responsive grid',            kind: 'tall' },
      { src: 'redesign/15.png', label: 'Revised goals',              kind: 'tall' },
    ],
  },
  {
    id: 'platform-redesign',
    n: '04',
    title: 'Platform Onboarding',
    subtitle: 'First-run experience for a B2B2C SaaS',
    role: 'Product Designer',
    year: '2022 — 2023',
    timeline: 'Oct 2022 — Mar 2023',
    platform: 'Web',
    team: '1 designer, 3 engineers',
    sector: 'B2B2C SaaS',
    kind: 'B2B2C SaaS',
    tile: 'sq',
    summary: 'Designed the first-run experience for a platform with two audiences — the admin who configures it and the end user who lives in it — and found a way to serve both without forking the product.',
    swatch: { from: '#181B1D', to: '#0B0D0E', mark: '#3E4448' },
    sections: [
      { id: 'context', title: 'Context', body: [
        'A platform sold to companies but used by their employees. Admins set it up once a quarter. End users open it every day. Both groups had been getting the same tour.',
        'Admin completion was 78%, which sounded fine until you looked at the sub-step where they\'re asked to invite their team — only 31% finished that.',
      ]},
      { id: 'split', title: 'A two-track first run', body: [
        'Forked the experience at the door: admins land on a configuration view, end users on a "what is this product even for" view. Each track is short — 4 steps for admin, 2 for end user.',
        'Crucially, end users can be productive before their admin finishes setup. The product degrades gracefully into a personal mode.',
      ]},
      { id: 'outcomes', title: 'What changed', kind: 'outcomes', items: [
        { num: '94%', label: 'Admin completion' },
        { num: '78%', label: 'Team-invite completion' },
        { num: '11d → 2d', label: 'Time to first end-user value' },
      ]},
    ],
    gallery: [
      { kind: 'wide', label: 'Admin setup', tone: '#101315' },
      { kind: 'sq', label: 'End-user welcome', tone: '#0E1112' },
    ],
  },
];

const RESUME = {
  name: 'Raz Silberman',
  title: 'Product Designer',
  blurb: 'Six years designing B2B and B2B2C SaaS products end-to-end — research, structure, interaction, visual, and the unglamorous follow-through that makes work actually ship.',
  contact: [
    { k: 'Email', v: 'hello@razsilberman.com' },
    { k: 'Location', v: 'Tel Aviv · remote-friendly' },
    { k: 'Read.cv', v: 'read.cv/raz' },
    { k: 'LinkedIn', v: 'linkedin.com/in/raz' },
  ],
  experience: [
    {
      role: 'Senior Product Designer',
      org: 'Quill (knowledge management)',
      when: '2023 — Present',
      where: 'Tel Aviv · hybrid',
      notes: [
        'Lead designer on the help center product (~3M monthly readers).',
        'Built and shipped the company\'s first design system; migrated four products onto it.',
        'Owned applied-AI navigation work — wrote the team\'s principles for AI surfaces.',
      ],
    },
    {
      role: 'Product Designer',
      org: 'Northbeam (B2B2C platform)',
      when: '2021 — 2023',
      where: 'Remote',
      notes: [
        'Redesigned first-run for a two-audience SaaS; admin completion 78% → 94%.',
        'Embedded with the analytics squad for a year — owned all dashboard surfaces.',
      ],
    },
    {
      role: 'Product Designer',
      org: 'Studio Faun (agency)',
      when: '2019 — 2021',
      where: 'Berlin',
      notes: [
        'Lead designer on six client engagements across fintech, climate, and healthcare.',
        'Founded the studio\'s component library practice.',
      ],
    },
  ],
  education: [
    { role: 'BFA, Visual Communication', org: 'Bezalel Academy of Arts and Design', when: '2015 — 2019' },
  ],
  speaking: [
    { role: 'Designing for AI uncertainty', org: 'Config (Figma) · panel', when: '2025' },
    { role: 'Tokens before components', org: 'Friends of Figma TLV', when: '2024' },
  ],
  capabilities: [
    'Product strategy', 'Information architecture', 'Interaction design', 'Visual design',
    'Design systems', 'Prototyping (React)', 'User research (mod. + unmod.)', 'Applied AI surfaces',
    'Design ops', 'Cross-functional facilitation',
  ],
};

window.PROJECTS = PROJECTS;
window.COMPANIES = COMPANIES;
window.RESUME = RESUME;
